/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.ImageIcon;

/**
 *
 * @author ITC
 */
public class Mainformdemo extends javax.swing.JFrame {
private InforPanel mthongtinPanel;
private EatPanel mfoodPanel;
private Body mbodypersonPanel;
    /**
     * Creates new form Mainformdemo
     */
    public Mainformdemo() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tplMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuthongtinuser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnudinhduongPanel = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuchisoPanel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        introduPanel = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnLogout = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mexitPanel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jMenu1.setText("Danh mục");

        mnuthongtinuser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuthongtinuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userperson.png"))); // NOI18N
        mnuthongtinuser.setText("Thông tin người dùng");
        mnuthongtinuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuthongtinuserActionPerformed(evt);
            }
        });
        jMenu1.add(mnuthongtinuser);
        jMenu1.add(jSeparator1);

        mnudinhduongPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food1.png"))); // NOI18N
        mnudinhduongPanel.setText("Dinh dưỡng món ăn");
        mnudinhduongPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnudinhduongPanelActionPerformed(evt);
            }
        });
        jMenu1.add(mnudinhduongPanel);
        jMenu1.add(jSeparator2);

        mnuchisoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dumbbell.png"))); // NOI18N
        mnuchisoPanel.setText("Chỉ số cơ thể");
        mnuchisoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuchisoPanelActionPerformed(evt);
            }
        });
        jMenu1.add(mnuchisoPanel);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hê thống");

        introduPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/introduction.png"))); // NOI18N
        introduPanel.setText("Giới thiệu");
        introduPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduPanelActionPerformed(evt);
            }
        });
        jMenu2.add(introduPanel);
        jMenu2.add(jSeparator3);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login01.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(btnLogout);
        jMenu2.add(jSeparator4);

        mexitPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit01.png"))); // NOI18N
        mexitPanel.setText("Thoát");
        mexitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mexitPanelActionPerformed(evt);
            }
        });
        jMenu2.add(mexitPanel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tplMainBoard)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuthongtinuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuthongtinuserActionPerformed
      if(mthongtinPanel == null ){
          mthongtinPanel  = new InforPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/userperson.png"));
         tplMainBoard.addTab("Thông tin người dùng", icon, mthongtinPanel, "Thông tin người dùng");
 }
       tplMainBoard.setSelectedComponent(mthongtinPanel);
    }//GEN-LAST:event_mnuthongtinuserActionPerformed

    private void mnudinhduongPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnudinhduongPanelActionPerformed
        if(mfoodPanel == null ){
          mfoodPanel  = new EatPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/monan.png"));
         tplMainBoard.addTab("Dinh dưỡng món ăn", icon, mfoodPanel, "Dinh dưỡng món ăn");
 }
       tplMainBoard.setSelectedComponent(mfoodPanel);
    }//GEN-LAST:event_mnudinhduongPanelActionPerformed

    private void mnuchisoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuchisoPanelActionPerformed
         if(mbodypersonPanel == null ){
          mbodypersonPanel  = new Body();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/chiso.png"));
         tplMainBoard.addTab("Chỉ số cơ thể", icon, mbodypersonPanel, "Chỉ số cơ thể");
 }
       tplMainBoard.setSelectedComponent(mbodypersonPanel);
    }//GEN-LAST:event_mnuchisoPanelActionPerformed

    private void mexitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexitPanelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mexitPanelActionPerformed

    private void introduPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduPanelActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this,true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_introduPanelActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       logindialog  login = new logindialog(this, true);
       login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainformdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainformdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainformdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainformdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainformdemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem introduPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mexitPanel;
    private javax.swing.JMenuItem mnuchisoPanel;
    private javax.swing.JMenuItem mnudinhduongPanel;
    private javax.swing.JMenuItem mnuthongtinuser;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
